services:
  chromadb:
    image: chromadb/chroma:0.6.0
    container_name: bratishka-chromadb
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped
    # Улучшенный healthcheck для ChromaDB
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - bratishka-network
    # Ограничения ресурсов для ChromaDB
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 512M
          cpus: '0.5'

  bratishka-bot:
    build:
      context: .
      dockerfile: Dockerfile
      # Оптимизация сборки с кэшированием
      args:
        BUILDKIT_INLINE_CACHE: 1
      # Используем кэш от предыдущих сборок
      cache_from:
        - bratishka-bot:latest
    container_name: bratishka-bot
    depends_on:
      chromadb:
        condition: service_healthy
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - DEFAULT_TIME_HOURS=${DEFAULT_TIME_HOURS}
      - MODEL_PATH=${MODEL_PATH}
      - MODEL_CTX=${MODEL_CTX}
      - MODEL_THREADS=${MODEL_THREADS}
      - MODEL_GPU_LAYERS=${MODEL_GPU_LAYERS}
      - MODEL_TEMPERATURE=${MODEL_TEMPERATURE}
      - MODEL_TOP_P=${MODEL_TOP_P}
      - MODEL_MAX_TOKENS=${MODEL_MAX_TOKENS}
      - CHROMA_HOST=${CHROMA_HOST_DOCKER}
      - CHROMA_PORT=${CHROMA_PORT}
      - DEBUG=${DEBUG}
      - LOG_LEVEL=${LOG_LEVEL}
      # Оптимизация производительности
      - OMP_NUM_THREADS=${OMP_NUM_THREADS}
      - MKL_NUM_THREADS=${MKL_NUM_THREADS}
      - OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE}
    volumes:
      - ./models:/app/models:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${DOCKER_MEMORY_LIMIT}
          cpus: '${DOCKER_CPU_LIMIT}'
        reservations:
          memory: ${DOCKER_MEMORY_RESERVATION}
          cpus: '${DOCKER_CPU_RESERVATION}'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - bratishka-network

volumes:
  chromadb_data:
    driver: local

networks:
  bratishka-network:
    driver: bridge
    name: bratishka-network
