services:
  chromadb:
    image: chromadb/chroma:0.6.0
    container_name: bratishka-chromadb
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
      - ANONYMIZED_TELEMETRY=False
    ports:
      - "8000:8000"
    volumes:
      - chromadb_data:/chroma/chroma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - bratishka-network

  bratishka-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bratishka-bot
    depends_on:
      chromadb:
        condition: service_healthy
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - DEFAULT_TIME_HOURS=${DEFAULT_TIME_HOURS:-2}
      - MODEL_PATH=${MODEL_PATH:-./models/model.gguf}
      - MODEL_CTX=${MODEL_CTX:-2048}
      - MODEL_THREADS=${MODEL_THREADS:-4}
      - MODEL_GPU_LAYERS=${MODEL_GPU_LAYERS:-0}
      - MODEL_TEMPERATURE=${MODEL_TEMPERATURE:-0.6}
      - MODEL_TOP_P=${MODEL_TOP_P:-0.95}
      - MODEL_MAX_TOKENS=${MODEL_MAX_TOKENS:-2048}
      - CHROMA_HOST=${CHROMA_HOST_DOCKER:-chromadb}
      - CHROMA_PORT=${CHROMA_PORT:-8000}
      - DEBUG=${DEBUG:-0}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - OMP_NUM_THREADS=${OMP_NUM_THREADS:-4}
      - MKL_NUM_THREADS=${MKL_NUM_THREADS:-4}
      - OPENBLAS_NUM_THREADS=${OPENBLAS_NUM_THREADS:-4}
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE:-1}
    volumes:
      - ./models:/app/models:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: ${DOCKER_MEMORY_LIMIT:-8G}
          cpus: '${DOCKER_CPU_LIMIT:-4.0}'
        reservations:
          memory: ${DOCKER_MEMORY_RESERVATION:-4G}
          cpus: '${DOCKER_CPU_RESERVATION:-2.0}'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    # Упрощенный healthcheck - проверяем только запуск сервиса
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/tmp/service_started') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - bratishka-network

volumes:
  chromadb_data:
    driver: local

networks:
  bratishka-network:
    driver: bridge
    name: bratishka-network
