services:
  postgres:
    image: postgres:16-alpine
    environment:
      TZ: ${TZ}
      PGTZ: ${TZ}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_ADMIN}
      POSTGRES_PASSWORD: ${DATABASE_ADMIN_PASSWORD}
      POSTGRES_NON_ROOT_USER: ${DATABASE_USER}
      POSTGRES_NON_ROOT_PASSWORD: ${DATABASE_USER_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh:ro
    ports:
      - "5442:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_ADMIN} -d ${DATABASE_NAME} && psql -U ${DATABASE_ADMIN} -d ${DATABASE_NAME} -c \"SELECT 1 FROM pg_roles WHERE rolname='${DATABASE_USER}'\""]
      interval: 10s
      timeout: 5s
      retries: 5
    command: >
      postgres
      -c shared_preload_libraries=pg_stat_statements
      -c pg_stat_statements.track=all
      -c max_connections=200
      -c shared_buffers=256MB
      -c effective_cache_size=1GB
      -c work_mem=4MB
      -c maintenance_work_mem=64MB

  bratishka-agent:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - BOT_USERNAME=${BOT_USERNAME}
      - DEFAULT_TIME_HOURS=${DEFAULT_TIME_HOURS}
      - MODEL_PATH=${MODEL_PATH}
      - MODEL_CTX=${MODEL_CTX}
      - MODEL_THREADS=${MODEL_THREADS}
      - MODEL_GPU_LAYERS=${MODEL_GPU_LAYERS}
      - CHROMA_DB_PATH=/app/chroma_db
      - DATABASE_HOST=${DATABASE_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
    volumes:
      - ./models:/app/models:ro
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env:ro

    restart: unless-stopped

    deploy:
      resources:
        limits:
          memory: 8G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'

    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  postgres_data:
    driver: local

networks:
  default:
    name: bratishka-network
